AllCops:
  TargetRubyVersion: 2.4
  Exclude:
    - db/schema.rb
    - db/migrate/*
    - node_modules/**/*
    - bin/**/*

Style/Documentation:
  Enabled: false

Metrics/LineLength:
  Max: 80
  AllowHeredoc: true
  AllowURI: true
  URISchemes:
    - http
    - https
  IgnoredPatterns:
    - '^#.*'
    - '\s*#.*'

Style/PercentLiteralDelimiters:
  PreferredDelimiters:
    default: ()
    '%i': '()'
    '%I': '()'
    '%r': '{}'
    '%w': '{}'
    '%W': '{}'

Bundler/OrderedGems:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - spec/**/*_spec.rb

Style/DotPosition:
  EnforcedStyle: trailing

Style/ClassAndModuleChildren:
  Enabled: false
